spring.application.name=AuthManagement
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

auth0.rsa.public-key=${rsa.public.key}
auth0.rsa.private-key=${rsa.private.key}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration